### ISSUE TITLE
Error when not in a Rails app

### ISSUE THREAD

**Issue by kerrizor** [voormedia/rails-erd#114]
Currently the gem will raise an exception if you run erd against a project that isn't a Rails project. Could we (should we) work to remove this, so its usable for ActiveRecord applications that aren't Rails? Is that useful in any way?

**Comment by supertinou** [comment]
It is definitely useful @kerrizor :-)

**Comment by bf4** [comment]
I don't see why not.  I run something similar in [metric_fu](https://github.com/metricfu/metric_fu/tree/master/etc) that I copied [from the twitter gem](https://github.com/sferik/twitter/blob/42ef8bce24875210e8949bfd0cde8c1f80dd86a0/etc/erd.rb)
