### ISSUE TITLE
pdf format missing

### ISSUE THREAD

**Issue by microspino** [voormedia/rails-erd#12]
I'm on OS X 10.6.7 + graphviz 2.26.3 installed via homebrew. Although I can generate .png fles without problems I'm unable to do the same with pdf. Heere is what I get:

Saving diagram failed!
Graphviz produced errors. Verify it has support for filetype=pdf, or use filetype=dot.
Original error: Format: "pdf" not recognized. Use one of: canon cmap cmapx cmapx_np dot eps fig gd gd2 gif gv imap imap_np ismap jpe jpeg jpg plain plain-ext png ps ps2 svg svgz tk vml vmlz vrml wbmp xdot

Any clue?

**Comment by tinynumbers** [comment]
FYI when I try to run `brew install graphviz --with-pangocairo` (per @jipiboily's suggestion) with the latest homebrew updates (after making sure cairo, pango, and graphviz have all been uninstalled), it issues a warning:

 `Warning: graphviz: --with-pangocairo was deprecated; using --with-pango instead!`

The compilation/installation completes successfully but the end result is still a Graphviz that can't handle PDFs:

```
rake aborted!
Saving diagram failed!
Graphviz produced errors. Verify it has support for filetype=pdf, or use filetype=dot.
Original error: Error: in routesplines, cannot find NORMAL edge
.../gems/rails-erd-1.3.0/lib/rails_erd/diagram/graphviz.rb:202:in `rescue in block in <class:Graphviz>'
.../gems/rails-erd-1.3.0/lib/rails_erd/diagram/graphviz.rb:197:in `block in <class:Graphviz>'
.../gems/rails-erd-1.3.0/lib/rails_erd/diagram.rb:142:in `instance_eval'
.../gems/rails-erd-1.3.0/lib/rails_erd/diagram.rb:142:in `save'
.../gems/rails-erd-1.3.0/lib/rails_erd/diagram.rb:120:in `create'
.../gems/rails-erd-1.3.0/lib/rails_erd/diagram.rb:74:in `create'
.../gems/rails-erd-1.3.0/lib/rails_erd/tasks.rake:41:in `block (2 levels) in <top (required)>'
.../bin/ruby_executable_hooks:15:in `eval'
.../bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => erd => erd:generate
```

**Comment by smenon8** [comment]
I have been facing the same issue. I am unable to create png or pdf of the dot files. I tried all the above solutions and none of them worked for me.

**Comment by kerrizor** [comment]
@smenon8 what errors are you getting? Can you give us more information, please?

**Comment by midwire** [comment]
I'm on Yosemite, and this worked for me...
```
brew uninstall pango cairo graphviz
brew install cairo pango
brew install graphviz --with-pango --with-cairo
```

**Comment by rsutaria** [comment]
I'm on MacOS Sierra (10.12.4) and the only way I could get past this error was by building from the sources.
Downloaded the source tarball from here:
http://www.graphviz.org/pub/graphviz/CURRENT/graphviz-working.tar.gz

Then, the usual:
./configure
make
make install

**Comment by parautenbach** [comment]
I can confirm @rsutaria's method: Building from sources is the only one that works for me on macOS Sierra 10.12.4.

**Comment by maryam-k** [comment]
@rsutaria's solution is the only one that worked for me on macOS Sierra 10.12.6.

**Comment by michaelbrawn** [comment]
Running High Sierra 10.13.5
The source file has moved
This worked for me.
```
curl "https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz" | tar xz
cd graphviz-2.40.1
./configure
make
make install
```
