### ISSUE TITLE
No attributes option

### ISSUE THREAD

**Issue by matthew-white** [voormedia/rails-erd#137]
I'm sure I'm just specifying something wrong on the command line, but I'm having trouble using the `--attributes=false` option:

```
. bundle exec erd --attributes=false

Loading application in 'myapp'...
Failed: NoMethodError: undefined method `false?' for #<RailsERD::Domain::Attribute:0x007fe5374d3400>
```

Any ideas? Thank you!

**Comment by haman29** [comment]
I tried the same thing, too. :)
If this option is used, it's done successfully.
```
$ bundle exec erd --attributes=inheritance
```

**Comment by matthew-white** [comment]
Thanks @haman29! That's much better, though a few of my classes have a `type` column. I feel like the `--attributes=false` functionality is written, it's just not clear that it's built into the command line. Hopefully a small fix...

**Comment by kerrizor** [comment]
@matthew-white it currently only claims to support "content", "foreign_key", and "inheritance" - what exact behavior would you expect passing "false" to result in?

**Comment by matthew-white** [comment]
I thought `false` was an option after reading the [customize page](http://voormedia.github.io/rails-erd/customise.html):

> The following output options are available in Rails ERD.

> ```
attributes             <type,...> | false
```

> ...
>
> To hide attributes altogether, set this option to `false`.

With this option, I would expect the diagram to include no attributes. Sometimes I'm interested in only the models and their associations and not the attributes of any of the models. This is especially true when there are many models: then adding attributes to the diagram can make it harder to read.

**Comment by forplayplay** [comment]
PR for this:

https://github.com/voormedia/rails-erd/pull/173
