### ISSUE TITLE
Graphviz produced errors. Verify it has support for filetype=pdf, or use filetype=dot.

### ISSUE THREAD

**Issue by reconstructions** [voormedia/rails-erd#139]
rails-erd isn't working for me since I upgraded to Rails 4.2.  I am seeing the same errors that tinynumbers does in [this closed issue](https://github.com/voormedia/rails-erd/issues/12).

Warning: graphviz: --with-pangocairo was deprecated; using --with-pango instead!

The compilation/installation completes successfully but the end result is still a Graphviz that can't handle PDFs.

**Comment by kerrizor** [comment]
Thanks for reporting this! We don't have control over how the graphviz formula via homebrew installs, but we can certainly update the documentation! Care to take a stab at that?

**Comment by reconstructions** [comment]
Sorry, but I wasn't able to find a solution to this problem.  If I do I will add my solution to the documentation in Issue #12.  Obviously rails-erd's dependencies are not within your control, but I agree it would be great if their correct configuration was documented.  Hopefully this is only affecting a handful of users, and someone more knowledgeable than myself will post a solution soon.
