### ISSUE TITLE
Auto-generate an rake db:migrate

### ISSUE THREAD

**Issue by gbataille** [voormedia/rails-erd#143]
Hi,

It would be great if there was an option to auto launch the erd task on a rake db:migrate. the Annotate-model gem does that.

I actually did it (ugly) on one of my project. I might try to propose a PR if I find the time to clean it up

**Comment by kerrizor** [comment]
If you want to put together a PR, I'd be happy to work with you on making it not ugly :)

**Comment by cherimarie** [comment]
This is done: https://github.com/voormedia/rails-erd/pull/148
