### ISSUE TITLE
enum issues

### ISSUE THREAD

**Issue by zxiest** [voormedia/rails-erd#144]
Hello,

I am getting the following:
Failed: TypeError: no implicit conversion of Symbol into Integer

It's not showing the error line but I think it's related to my Rails 4 enums:
    `enum role: %i(admin agentadmin agentuser merchantadmin merchantuser)`

**Comment by kerrizor** [comment]
Are you still able to generate this error, and can you share the full stack trace or output from when it occurs?

**Comment by pranavpr** [comment]
Yes, I am also facing the same issue in Rails 4.2.1 using graphviz-2.38.0 on Mac OSX.

**Comment by Leventhan** [comment]
@pranavpr Any updates on this issue?

**Comment by kerrizor** [comment]
Using my Rails 4.2 test app, I was able to successfully generate an ERD for a model with an enum column. I'm going to close this for now, assuming that we accidentally fixed this somewhere along the way.
