### ISSUE TITLE
displaying ERD by modules

### ISSUE THREAD

**Issue by ostrochovsky** [voormedia/rails-erd#156]
Hello,

I am building an application divided into several modules (models, views, controllers - all in separate modules/subdirectories). It could be very nice to have option to generate model diagram grouped by modules - entities from each modules in its own "box", but still interconnected correctly, and optionally, filter what to generate also by modules (for having separate sub-ERD for each module separately).

Graphviz has this option and implements it by subgraphing, examples:
http://www.graphviz.org/content/fdpclust
http://www.graphviz.org/content/cluster

Do you plan to add such feature in near future? If no, I could try to do some extension, if you would give me some hints for "best practise", how to incorporate it into your great gem, and provide it to you and the community.

Thanks in advance.

Jano

**Comment by kerrizor** [comment]
rails-erd is primarily focused on graphing the ActiveRecord relationships between models, but there's no reason it couldn't expand to display controller and/or view relationships! First step, I think, would be to figure out what sort of data structure would best represent these connections, and get that working - are there existing hooks to relate these object to each other, if they're not ActiveRecord related (ie `has_many` and 'belongs_to`)

**Comment by ostrochovsky** [comment]
I was not exact enough, currently controler and view are not very
interesting for me, but ActiveRecord models separated between different
modules are...

for example:

I have some modules and some models in each:

app/models/accounts.rb
app/models/accounts/user.rb
...
app/models/game.rb
app/models/game/server.rb
...

there are relations between models in different modules, e.g.:

class Game::Server < ActiveRecord::Base
  belongs_to :user, class_name: "Accounts::User"
end

I would like to have Game models (classes) grouped in subgraph called Game,
and Accounts models (classes) grouped in subgraph called Accounts, etc.

how could I save also Graphviz .dot source? I could for example make
conversion script, when it will find ActiveRecord class name in the form
Module::Model, it will include it into subgraph and generate final output
then... or maybe you'll see more elegant/efficient/smart solution...

thanks

Jano

**Comment by kerrizor** [comment]
AH! Apologies for not understanding. Yes, I think this would be a good to offer, perhaps as a command line option.

**Comment by ostrochovsky** [comment]
Hello,

I created a Ruby script snippet (part of bigger solution beyond the scope of rails-erd) to accomplish this task:

``` ruby
system "bin/rake erd filetype=dot"
system 'dot erd.dot -Tpdf > erd.pdf'
erd_dot_contents = File.read('erd.dot')
models_array = erd_dot_contents.split(/(\s|<|>|\"m_|\")+/)
models_array = models_array.find_all{|item| item =~ /::/ }
modules_array = []
models_array.each_with_index do |item,index|
        item = item.split('::')
        modules_array.push(item[0])
end
modules_array.uniq!.sort!
modules_array.each do |module_name|
        #erd_dot_contents.gsub!(//,"")
        erd_dot_contents.gsub!(/^node\[( shape)/,"node[ style=filled, color=yellow,\\1")
        erd_dot_contents.gsub!(/^(edge\[)/,"splines=ortho;\n\\1")
        erd_dot_contents.gsub!(/(^\"m_#{module_name}::.*?)(((^\"m_)(?!#{module_name}))|((^\s+\"m_)(.*)))/m,"subgraph cluster_#{module_name} { fontcolor=red; fontsize=20; label=#{module_name}; style=filled; fillcolor=lawngreen; pencolor=transparent; \\1}\n\\2")
end
File.open('erd_modular.dot', "w") { |file| file.puts erd_dot_contents }
system 'dot erd_modular.dot -Tpdf > erd_modular.pdf'
```
Here is how model looks like before and after modification of source dot-file by this snippet:

![erd](https://cloud.githubusercontent.com/assets/13231994/8766475/7e2b7182-2e39-11e5-9289-e90fcc44c29f.png)
![erd_modular](https://cloud.githubusercontent.com/assets/13231994/8766474/7e29d174-2e39-11e5-8a0d-a760c89007f4.png)

Feel free to use (public domain).

Caveats (ugly points):

1. Some subgraphs/clusters are too close to each other and some nodes are not centered well inside the cluster and are just on cluster boundaries. It is not pretty, it should be placed more aesthetically, I googled a lot and tried to fix it, but with no success, maybe it's the limitation of my knowledge of Graphviz, or limitation of Graphviz itself. Advices from more experienced graphwizzards are welcome. Partial (tested) workaround could be generate module labels with variable-length line, e.g. ----------------------------- Accounts -----------------------------, it helps to widen clusters and visually seperate clusters and their nodes from other clusters and their nodes.

2. Formats, styles and colors hardcoded in the script, it would be better to configure it outside the script (command-line, configuration file).

I am OK with current state of this implementation, but anybody is welcome to improve it further, or maybe incorporate modular output as command-line option in rails-erd. Or drop me a line here, if you'll find some bugs or will have further improvement ideas.

Jan Ostrochovsky

**Comment by mtyeh411** [comment]
+1

**Comment by kerrizor** [comment]
AWESOME! <3 for sharing this.. I'll see if I can work this into 1.5 (which wow, is looking like a big release!)
