### ISSUE TITLE
Don't know how to build task 'erd'

### ISSUE THREAD

**Issue by sps196** [voormedia/rails-erd#16]
Hi,

rake doesn't seem to know about the erd task:

$ rake erd
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)  
rake aborted!  
Don't know how to build task 'erd'                                              

(See full trace by running task with --trace)                                   

I've also tried this with rake 0.8.7, and aside from the deprecation warning disappearing nothing changed.

This is my Gemfile:

$ cat Gemfile

source :rubygems                                                                

group :development do  
  gem "rails-erd"  
end

And bundle claims it's all installed correctly:

$ bundle install  
Using activesupport (3.0.9)  
Using builder (2.1.2)  
Using i18n (0.5.0)  
Using activemodel (3.0.9)  
Using arel (2.0.10)  
Using tzinfo (0.3.29)  
Using activerecord (3.0.9)  
Using ruby-graphviz (0.9.21)  
Using rails-erd (0.4.5)  
Using bundler (1.0.15)  
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.

$ bundle show rails-erd  
/usr/lib/ruby/gems/1.8/gems/rails-erd-0.4.5

I'm pretty stumped. Here's a full rake trace:

$ rake erd --trace
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)  
rake aborted!  
Don't know how to build task 'erd'  
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task_manager.rb:49:in `[]'      
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:111:in`invoke_task' 
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in`each'  
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:62:in`run'  
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:59:in`run'  
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/bin/rake:32
/usr/bin/rake:19:in `load'
/usr/bin/rake:19

Sam

**Comment by Adithya-copart** [comment]
For others who encounter the ```NoMethodError: undefined method `application' for Rails:Module```,
I was able to monkey-patch the [name method](https://github.com/voormedia/rails-erd/blob/c3b680674b8a773cabed317847e789099bd4e54e/lib/rails_erd/domain.rb#L51-L53) in domain class to return nil and got around this.

Used outside Rails with ActiveRecord 5.1.1

```
 RailsERD::Diagram::Graphviz.create
NoMethodError: undefined method `application' for Rails:Module
	from /Users/adpentela/.rvm/gems/ruby-2.4.0/gems/rails-erd-1.5.2/lib/rails_erd/domain.rb:52:in `name'
	from /Users/adpentela/.rvm/gems/ruby-2.4.0/gems/rails-erd-1.5.2/lib/rails_erd/diagram/graphviz.rb:179:in `block in <class:Graphviz>'
	from /Users/adpentela/.rvm/gems/ruby-2.4.0/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:126:in `instance_eval'
	from /Users/adpentela/.rvm/gems/ruby-2.4.0/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:126:in `generate'
	from /Users/adpentela/.rvm/gems/ruby-2.4.0/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:119:in `create'
	from /Users/adpentela/.rvm/gems/ruby-2.4.0/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:74:in `create'
	from (irb):11
	from /Users/adpentela/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'

```

**Comment by ADTC** [comment]
Try `bundle exec erd` as this will directly execute it instead of running it as a Rails Task.
