### ISSUE TITLE
unable to produce pdf in Yosemite 10.10.5

### ISSUE THREAD

**Issue by ericbrooke** [voormedia/rails-erd#160]
Staring with new Mac today

```
failed: RuntimeError: Saving diagram failed!
Graphviz produced errors. Verify it has support for filetype=pdf, or use filetype=dot.
Original error: Error: /var/folders/p_/dnysjwp55jl5ymqgrwg46r4w0000gq/T/graphviz.rb20150814-51440-o5or26: syntax error in line 276 near ','
```

I can produce a .dot file and it does have contents.

Tried the variations at https://github.com/voormedia/rails-erd/issues/12:

```
brew install cairo pango graphviz
```

No luck

I tried to open .dot file in Omnigraffle and I got this error:

-[NSConcreteAttributedString rangeOfCharacterFromSet:options:range:]: unrecognized selector sent to instance 0x608000424960

Line 30: >];

**Comment by kerrizor** [comment]
<3 for the report! I haven't dug deeply into the interface with Graphviz, but I'll take a look. Could you lend a hand? It'd be awesome if you had time to:

- confirm which version of rails-erd you're using?
- if you're not on the latest (1.4.2 as of right now) install it and try again?
- Which version of Rails?
- What column types are you using? We've got an bug with `:enum` columns, but maybe there's another column type, less commonly used, that's in your schema that we're also not accounting for yet
- if your project one you can share so I can reproduce?

**Comment by kerrizor** [comment]
see also #139

**Comment by reconstructions** [comment]
I have never found a solution to this problem (reported as #139).  I am using rails-erd 1.4.6, OS X Yosemite 10.10.4, and Rails 4.2.4.  I have gotten the message, "Verify it has support for filetype=pdf, or use filetype=dot" in previous attempts to fix this.  This time I get the message, "Verify that Graphviz is installed and in your path, or use filetype=dot".  I can also output a dot file, but it also seems to be corrupted.

**Comment by reconstructions** [comment]
Got it working almost immediately after posting above.  I simply ran the installer for the app from the Graphviz [site](http://www.graphviz.org/Download_macos.php).  That did what no amount of Brew cycling could not.  The command line Rails gem commands work fine now.  I used the 2.36 Mountain Lion version.

**Comment by reconstructions** [comment]
I have reproduced this error when outputting a graph with a single entity containing two string attributes:

rake erd:generate only="Musician" filetype="dot"

I cannot open the enclosed file in OmniGraffle 6.1.4 without getting the aforementioned error...

[erd.dot.zip](https://github.com/voormedia/rails-erd/files/190181/erd.dot.zip)
