### ISSUE TITLE
How to generate a diagram based off one model and  all of its children

### ISSUE THREAD

**Issue by palidanx** [voormedia/rails-erd#161]
First off, thanks for  the tool!

I was curious, is it possible to generate a diagram based off one root model with all of its children?

For example you might have

title
:has_many products

products
:has_many skus

so the diagram would have title -->  products -->  skus

thanks!

**Comment by palidanx** [comment]
I ended up writing some a little hacky, but it works

https://github.com/palidanx/rails-erd/blob/master/lib/rails_erd/custom.rb

**Comment by kerrizor** [comment]
Thanks! I was thinking about how useful this would be for focusing in on untangling models from each other along seams, when refactoring or breaking up monoliths. I'll take a look at your code, but if you'd like to propose it as a PR that would be awesome :)

**Comment by jamescway** [comment]
@palidanx could you describe how to use your script?

**Comment by palidanx** [comment]
Once you merge custom.rb into the source base you can

RailsERD::Custom.new( "User", "user.svg", 0)

The first param is the name of the class
The second param is the name of the svg file
The third param is number of levels you would like to iterate.  So for example, specifying 0 gets you only the root object.  Specifying 1 gets all children.  Specifying 2 gets all second level objects.  It checks to see what objects have already been seen so you the script doesn't run forever.

**Comment by jamescway** [comment]
@palidanx thanks for the help.  I [forked](https://github.com/jamescway/rails-erd/pull/1) the repo to get something working.  Will try to submit something upstream.

**Comment by kerrizor** [comment]
Please do. This is an active project, and we'd love to get this work back in. <3

**Comment by kerrizor** [comment]
Can this be accomplished with `--only` and `--only_recursive_depth`?

**Comment by vanboom** [comment]
I am looking to do this - any tips?  Looks like this issue was closed without a resolution?

**Comment by vanboom** [comment]
--only_recursion_depth does not work when only one model is given for --only.  Put a comma: 

```
erd --only_recursion_depth=5 --only User,
``
and it works.
