### ISSUE TITLE
Missing Helper File

### ISSUE THREAD

**Issue by ahnbizcad** [voormedia/rails-erd#163]
When I try to run `bundle exec erd' I get

Failed: AbstractController::Helpers::MissingHelperError: Missing helper file `helpers//users/my_computer_user_name/path_to/my_app_name/app/helpers/application_helper.rb_helper.rb`

**Comment by andrius** [comment]
same for me

**Comment by kerrizor** [comment]
What version of Rails/Ruby are you running against?
