### ISSUE TITLE
Unable to generate ERD 

### ISSUE THREAD

**Issue by Moondee** [voormedia/rails-erd#164]
I got: 

rake erd
Loading application environment...
Loading code in search of Active Record models...
rake aborted!
Active Record was not loaded.
/Users/.rvm/gems/ruby-1.9.3-p125/gems/rails-erd-1.4.2/lib/rails_erd/tasks.rake:34:in `block (2 levels) in <top (required)>'
/Users/.rvm/gems/ruby-1.9.3-p125/bin/ruby_executable_hooks:15:in`eval'
/Users/.rvm/gems/ruby-1.9.3-p125/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => erd => erd:generate => erd:load_models

any idea?

**Comment by Moondee** [comment]
also:

bundle exec erd
Loading application in 'project'...
Failed: NameError: uninitialized constant RailsERD::CLI::ActiveRecord

**Comment by kerrizor** [comment]
You're running this on a Rails project, correct?

**Comment by kerrizor** [comment]
I just did a clean room install and was able to cleanly generate a graph against a Rails 4.2 project.

**Comment by Moondee** [comment]
Yeah , I have Ruby 1.9.3 and Rails 3.2.19. Do you think my Rails version could cause the issue?
Thanks

**Comment by kerrizor** [comment]
Possibly. I built a small Rails 3.2.1/Ruby 1.9.3 app to test this, and was able to successfully generate an ERD.

**Comment by kerrizor** [comment]
We'll need to build a 3.2.19/1.9.3 app to test this against.

**Comment by LimeBlast** [comment]
I'm having the same issue on a new Suspenders project. It's not a totally fresh project, as I've been working on it for about a week, but I'm getting the same issue when running `bundle exec rake db:migrate`.

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ bundle exec rake db:migrate
rake aborted!
NameError: uninitialized constant Erd
/vagrant/lib/tasks/auto_generate_diagram.rake:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:658:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:658:in `run_tasks_blocks'
/var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/application.rb:452:in `run_tasks_blocks'
/var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/engine.rb:453:in `load_tasks'
/vagrant/rakefile:6:in `<top (required)>'(See full trace by running task with --trace)
```

**Comment by macumber** [comment]
I'm having the same issue

**Comment by balogic** [comment]
run `erd` in the root of the application
before that do,
`sudo apt-get install graphviz graphviz-dev`
`gem install ruby-graphviz`
It works for me :white_check_mark:

**Comment by 0215526** [comment]
I got the same issue with rails 5.1.3 ruby 2.4.1.

I know it's not supposed to for efficiency, but removing require: false in Gemfile solved it for me.

**Comment by gueyome** [comment]
> I got the same issue with rails 5.1.3 ruby 2.4.1.
> 
> I know it's not supposed to for efficiency, but removing require: false in Gemfile solved it for me.

Hello, where did you remove require: false in Gemfile?

**Comment by edusantana** [comment]
> gem install ruby-graphviz

This did not work for me.

```
$ bundle exec erd
Loading application in 'overmediacast-api'...
Failed: NameError: uninitialized constant RailsERD::CLI::ActiveRecord
```

**Comment by edusantana** [comment]
@dishangyijiao I'm using a project with MongoDB, without ActiveRecord.

**Comment by karolzmijewski** [comment]
I'm facing the same issue

**Comment by kerrizor** [comment]
@edusantana Which ORM are you using?

**Comment by edusantana** [comment]
Thanks @kerrizor but I no longer have access to the code. 👍🏽
