### ISSUE TITLE
Running ERD crashes with "Failed: TypeError: Choice is not a class"

### ISSUE THREAD

**Issue by sneakernets** [voormedia/rails-erd#165]
In my rails app I have a "Choice" model for showing ownership of chosen answers by users to questions on a small quiz. However when I run ERD I get this error:

```
Failed: TypeError: Choice is not a class
    from /app/models/choice.rb:1:in `<top (required)>'
```

Here is my model:

```ruby
class Choice < ActiveRecord::Base
  belongs_to :question
end
```
Can anyone help me?
Thanks

**Comment by kerrizor** [comment]
Is `Choice` alphabetically the first model in your app?

What command are you using? `bundle exec erd`?

Which version of Rails and rails-erd are you using?

**Comment by sneakernets** [comment]
Branch is the first model, followed by Choice.

I am using `bundle exec erd`.  Rails version is 3.2.22 and Ruby version is 2.2.2.

**Comment by kerrizor** [comment]
We're using the `Choice` gem to handle CLI configuration options, and I'd guess there's a name conflict happening in here somewhere. Sorry about that! Try (temporarily) renaming your model's name? That's a PITA for you, I know, but it'd get it to work. We may need to move to a different, more uniquely named tool on our side to avoid this issue. :disappointed:

**Comment by sneakernets** [comment]
At least now I know! :smile: Thanks for investigating this! The name of the model may change soon anyway due to refactoring so this won't be an issue.

**Comment by evilbikes79** [comment]
Running into this issue as well

**Comment by kerrizor** [comment]
Opening an issue for this. <3
