### ISSUE TITLE
NoMethodError: undefined method `start_with?' for nil:NilClass in Domain#check_habtm_model

### ISSUE THREAD

**Issue by fschwahn** [voormedia/rails-erd#177]
Hi,
I'm getting this error on my project, I think the reason is that I'm using the gem `active_type`, which is creating anonymous classes where `model.name` is nil. I patched my local version of the gem with the following code (in the `Domain`-class)

```ruby
def check_model_validity(model)
  if model.abstract_class? || model.table_exists?
    if model.name.nil?
      raise "model.name is nil"
    else
      true
    end
  else
    raise "table #{model.table_name} does not exist"
  end
rescue => e
  warn "Ignoring invalid model #{model.name} (#{e.message})".squish
end
```

I changed the control flow a bit, because the previous one would not work with this change anymore. I'm not sure if this change is in scope for this project, but I can put together a pull request if you think this is a worthwhile addition.

All the best,
Fabian

**Comment by kerrizor** [comment]
Thanks for reporting this! It is definitely worth a PR - thanks!

**Comment by kerrizor** [comment]
Fixed!
