### ISSUE TITLE
undefined method `attribute_names'

### ISSUE THREAD

**Issue by daveshah** [voormedia/rails-erd#195]
Trying this Gem out for the first time. I'm using Ruby 2.3.0 and Rails 4.2.6.
When running
```bundle exec erd --attributes=false```
I end up with
```
Loading application in 'my_app_name'...
Failed: NoMethodError: undefined method `attribute_names' for Choice:Module
Did you mean?  attr_internal
```
Was curious to know if someone has run into this problem before or if it could possibly be something on my end.
Thx!

**Comment by kerrizor** [comment]
My guess is that you have a model in your app called `Choice`? We use a gem of that name to pick up command line options, and it has caused this issue before. It's on my hit list, for sure :(

**Comment by kerrizor** [comment]
Going to close this for now - let me know if I should keep it open! ❤️
