### ISSUE TITLE
rails-erd does not recognize models from engine correctly

### ISSUE THREAD

**Issue by foomip** [voormedia/rails-erd#20]
When you mount an engine that contains models, the models are not recognized and an error is thrown.

In my case, we created a rails 3.1 mountable plugin called nms-cmdb and we are getting the following error output when running the 'rake erd' command:

$ rake erd --trace
** Invoke erd (first_time)
** Invoke erd:generate (first_time)
** Invoke erd:options (first_time)
** Execute erd:options
** Invoke erd:load_models (first_time)
** Execute erd:load_models
Loading application environment...
** Invoke environment (first_time)
** Execute environment
Loading code in search of Active Record models...
rake aborted!
wrong constant name Nms-cmdb
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:378:in `const_defined?'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:378:in `local_const_defined?'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:365:in `block in qualified_const_defined?'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:364:in `each'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:364:in `inject'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:364:in `qualified_const_defined?'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:125:in `block in watch_namespaces'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:123:in `map'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:123:in `watch_namespaces'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:636:in `new_constants_in'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:455:in `load_file'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:342:in `require_or_load'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:302:in `depend_on'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:214:in `require_dependency'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/engine.rb:416:in `block (2 levels) in eager_load!'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/engine.rb:415:in `each'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/engine.rb:415:in `block in eager_load!'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/engine.rb:413:in `each'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/engine.rb:413:in `eager_load!'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/application/railties.rb:8:in `each'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/application/railties.rb:8:in `all'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails/engine.rb:411:in `eager_load!'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rails-erd-0.4.5/lib/rails_erd/tasks.rake:23:in `block (2 levels) in <top (required)>'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/ruby1.9.2_railspre/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/usr/local/ruby1.9.2_railspre/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/usr/local/ruby1.9.2_railspre/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/usr/local/ruby1.9.2_railspre/lib/ruby/gems/1.9.1/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/usr/local/ruby1.9.2_railspre/bin/rake:19:in `load'
/usr/local/ruby1.9.2_railspre/bin/rake:19:in `<main>'
Tasks: TOP => erd => erd:generate => erd:load_models

**Comment by ZhijieWang** [comment]
I have gem "acts-as-taggable-on". However, erd does not recognize the "tag" model.

**Comment by bf4** [comment]
How so?  Example? Version of gems, ruby?

**Comment by ZhijieWang** [comment]
Sorry for not attach these info earlier. 

The Gem is direct pulling from https://github.com/ready4god2513/rails-erd/tree/rails-4.2-support-fix.

This may not be the appropriate place to file the bug report.

**Comment by bf4** [comment]
Without more info errors or to reproduce there is not much we can do.
If you can't figure it out or fix it with all the info, all the more
so us with only a gem name and reported unexpected results.

**Comment by ZhijieWang** [comment]
It is not an unexpected results. Rails-erd have not officially supported Rails 4.2 and I am using a hot fix by someone else.

If you need,

Ruby 2.1.3
Rails 4.2.0
acts-as-taggable-on latest

The erd file properly outputs my model diagram, however fails to pickup tag model defined in "act-as-taggable" gem.

**Comment by kerrizor** [comment]
@ZhijieWang could you open a new issue with these details?

**Comment by IamNaN** [comment]
Just a quick follow up because I don't understand the resolution of this issue. rails-erd does not pick up tables in engines? Or should it?

We have three engines (of our own making) in our rails 4.2 app, we're not using the acts-as-taggable-on gem, and I'm not getting the tables used by those engines. I tried the `only=` option thinking it might force them in there.

Specifically, app has a User model and a survey system mounted as an engine. Responses in the survey engine are loosely tied to users in the app (user.id <--> responder_guid). Obviously rails-erd isn't going to magically know how to do associate those tables without some hinting, but I thought the tables would still render.

**Comment by kerrizor** [comment]
@IamNaN rails-erd looks at ActiveRecord relationships, not at tables, so unless you have an AR relationship to something coming in from an engine, it isn't going to find it.

Should it? Possibly. Not every table in DB backing a Rails app is going to be related to a model, and not every object or concept in a Rails app is going to be an AR model. We /could/ draw the line by examining, instead of objects, the schema (or structure) but our guesses about the foreign keys, while usually right, wouldn't _always_ be right. :/

**Comment by IamNaN** [comment]
> so unless you have an AR relationship to something coming in from an engine, it isn't going to find it.

...Our engines are rails though, with AR models to back them. Those models are not under the app folder however. Could this be an issue?

**Comment by kerrizor** [comment]
Ah! Yes that'd do it. I'll open up a new issue for this and see if I can
"easily" get that in (or at least provide a way for specifying a dir other
than app)

**Comment by spacechurro** [comment]
Poked around a bit and I was able to get more and more engine models added to the generated graph with every successive run through the code below in rails console. Looks like it ended up loading all the models I needed from the engine after 4 runs. Works but really weird.

```ruby
require "rails_erd/diagram/graphviz"
Rails.application.eager_load!
RailsERD::Diagram::Graphviz.create
```

Running rails-erd 1.5.0 and rails 4.2.7

**Comment by spacechurro** [comment]
Ahh. I see `ActiveRecord::Base.descendants.count` going up with each call. So as long as you have all the models you need loaded in console, then it should work since `Domain#generate` uses ``ActiveRecord::Base.descendants`.

 https://github.com/voormedia/rails-erd/blob/master/lib/rails_erd/domain.rb#L27
