### ISSUE TITLE
blank erd.pdf generated

### ISSUE THREAD

**Issue by Tonkpils** [voormedia/rails-erd#200]
I've added this gem with a clean install of `Graphviz` on OSX El Capitan 10.11.4. 

Rails 4.2.6
Ruby 2.2.3

When I run `bundle exec erd`, it spews out a couple of warnings and 

```
Generating entity-relationship diagram for 515 models...
Warning: Ignoring invalid model ...
Warning: Ignoring invalid assocation ... 
... more warnings
Diagram saved to 'erd.pdf'.
```

The generated PDF is completely empty

**Comment by kerrizor** [comment]
Interesting! Something is clearly not working here; with 515 models, I'd expect at least ONE to be valid :) Can you do 2 things for me? Can you share the entire error output, and could you also attempt to generate just a DOT file instead of a PDF? That would help narrow down the cause. Oh, and also do an `erd --version` for me?

**Comment by Tonkpils** [comment]
Sure! I should've read the homepage a bit closer before posting the issue. It does seem like it's generating a valid DOT file. I installed the GraphViz app and was able to open the generated DOT file. 

```
Warning: Ignoring invalid model ActiveType::Object (table objects does not exist)
Warning: Ignoring invalid model Inbox (table inboxes does not exist)
Warning: Ignoring invalid model Report (table reports does not exist)
Warning: Ignoring invalid association :messages on User (model Ahoy::Message exists, but is not included in domain)
```

```
erd --version
RailsERD 1.4.7
```

**Comment by kerrizor** [comment]
Ah! Good to hear it sorted itself. I'll make an issue to check for Graphviz (or at least, not claim we successfully created a PDF when we didn't!)

**Comment by Tonkpils** [comment]
@kerrizor just to be sure, I did have Graphviz installed when the PDF was being generated blank. I did however, re-install it with homebrew with the `--with-app` to be able to open the DOT file in the native app. 

Even after installing it that way, the PDF generated was still blank so I think it may be an issue with how the PDF is being generated.

**Comment by Tonkpils** [comment]
Hmm, I think this may actually be an issue with the PDF reader? I generated a pdf with the dot tool and it created the same blank pdf (as viewed on Acrobat Reader). However, when looking at it through the Finder preview it shows the diagram...


![image](https://cloud.githubusercontent.com/assets/1507561/14718393/6bc3246c-07c4-11e6-99b3-778133cb6e70.png)

Very odd...

**Comment by emarthinsen** [comment]
FWIW, I have the exact same problem. The PDF, when opened with Acrobat Pro on OSX is completely blank. Opening it with Preview makes it visible. Opening it with Adobe Illustrator also makes it visible. I did notice that the artboard size in Illustrator wasn't large enough to hold the entire diagram. Perhaps that is part of the problem?
