### ISSUE TITLE
Using cluster:true requires Ruby 2.3 or better

### ISSUE THREAD

**Issue by cobbr2** [voormedia/rails-erd#227]
I'm trying to explore different layout options with .erdconfig, and when I chose `cluster: true`, I got

NoMethodError - undefined method `dig' for []:Array:
  rails-erd (1.5.0) lib/rails_erd/domain/entity.rb:96:in `namespace'

Apparently, `dig` was introduced in Ruby 2.3.0; we're using 2.1.5 in this repo -- and the rails-erd README.md states 1.9.3.

**Comment by FTorrenegraG** [comment]
I have the same problem

**Comment by kerrizor** [comment]
Argh... that's a pain. That means at the very least we don't have a test for this since the Travis 1.9.3 build is passing. I saw your PR #228 I'll comment more over there.
