### ISSUE TITLE
Rails 4? Rails 5?

### ISSUE THREAD

**Issue by alexmc6** [voormedia/rails-erd#230]
The documentation says this is for Rails 3 . However I am starting out with Rails 5 and cannot "rake erd". Can you please modify the documentation to say whether or not it is compatible with rails 4 or 5, and whether the rest of the documentation stays the same. 

Thanks.

$ bundle exec rake erd
rake aborted!
Don't know how to build task 'erd' (see --tasks)

(MacOS X Sierra, homebrew, rake 11.something
$ rails -v
Rails 5.0.0.1)

**Comment by alexmc6** [comment]
Sorry if this is a duplicate of https://github.com/voormedia/rails-erd/issues/174

**Comment by alexmc6** [comment]
OK - after some more testing I can confirm that rails-erd does seem to work fine in Rails5. Thank you very much!

**Comment by kerrizor** [comment]
Ah, ok, no problem! I'm going to go ahead and close this, @alexmc6 but if you have a minute, could you tell me what the problem was? We might need to update our documentation!

**Comment by crantok** [comment]
@alexmc6 Please would you state problem and resolution if you can remember what it was. I'm getting the same message in rails 5

**Comment by crantok** [comment]
Follow up: I had same problem. I was trying to run erd as a rake task as suggested by the [docs page](https://voormedia.github.io/rails-erd/install.html#generate) to generate a diagram with a single command.
Once I read the REAMDE.md instead, I realised I could just call the erd executable directly. That worked.
