### ISSUE TITLE
Using --only with a single model from command line

### ISSUE THREAD

**Issue by vzamanillo** [voormedia/rails-erd#231]
I was looking for an example of using `--only` from the command line, I suppose only expects an String to conform an array

`--only="ModelA,ModelB"`

But I don't know how to pass a single model, actually I am doing something like this:

`--only="ModelA, "`

with

`--only="ModelA"`

fails because is an String not an array.

**Comment by kerrizor** [comment]
Oh! That's an awesome bug! We should fix that maybe..

**Comment by kerrizor** [comment]
I was unable to reproduce this error in the 1.5.0 release. Closing for now, but if you'd like to reopen, can you also supply your version of RailsERD?

**Comment by vzamanillo** [comment]
Hey!! I am using 'rails-erd', '1.5', I will test again and I will let you know, it could be an error produced by me.
