### ISSUE TITLE
Exclude transient AR tables

### ISSUE THREAD

**Issue by kerrizor** [voormedia/rails-erd#232]
Reported in #229, that if you attempt to generate an ERD in the middle of a `db:migrate` action while transient migration objects/tables exist, they'll show up on your ERD. We should exclude `ActiveRecord::InternalMetadata` and `ActiveRecord::SchemaMigration` by `merge`ing with any user-supplied exclude options.

**Comment by moritzmair** [comment]
while this remains unfixed, is there a workarround for this?

**Comment by kerrizor** [comment]
@moritzmair Yes, you can specifically `exclude` models from the output via CLI flags or the config file. `README` has info that should get you started (and if it needs more, let me know!)
