### ISSUE TITLE
Feature Request: Crow's Foot Notation

### ISSUE THREAD

**Issue by doncadavona** [voormedia/rails-erd#234]
Please add the option to use **Crow's Foot** notation aside from the the Simple and Bachman notations for ERD relationships or participation.

This option would be very useful:
`rake erd notation=crow`

For more info about Crow's Foot notation please see:
[http://www2.cs.uregina.ca/~bernatja/crowsfoot.html](http://www2.cs.uregina.ca/~bernatja/crowsfoot.html)

**Comment by kerrizor** [comment]
I believe this is an option currently, using `notation=crowsfoot`

**Comment by doncadavona** [comment]
@kerrizor  Oh indeed it's already available! I didn't know as I have not seen it in the docs. Shouldn't this be in the docs? Thanks!

**Comment by gumatias** [comment]
Agree with @doncadavona . The information on the options available for `notation` is difficult to find in the docs. This is the only place I could find it.
