### ISSUE TITLE
Error while running rails-erd -> Verify that Graphviz is installed and in your path, or use filetype=dot

### ISSUE THREAD

**Issue by kavita-chitnis** [voormedia/rails-erd#278]
I installed the following on my Ubuntu->

sudo aptitude install graphviz
gem 'rails-erd'

When I run, 
rake erd, i get the following error. 

Verify that Graphviz is installed and in your path, or use filetype=dot.
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram/graphviz.rb:211:in `rescue in block in <class:Graphviz>'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram/graphviz.rb:202:in `block in <class:Graphviz>'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:169:in `instance_eval'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:169:in `save'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:120:in `create'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:74:in `create'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/tasks.rake:55:in `block (2 levels) in <top (required)>'
/home/kavita/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/kavita/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `zero?' for nil:NilClass
/home/kavita/.rvm/gems/ruby-2.1.5/gems/ruby-graphviz-1.2.3/lib/graphviz/utils.rb:58:in `output_from_command'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/ruby-graphviz-1.2.3/lib/graphviz.rb:600:in `output'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram/graphviz.rb:204:in `block in <class:Graphviz>'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:169:in `instance_eval'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:169:in `save'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:120:in `create'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:74:in `create'
/home/kavita/.rvm/gems/ruby-2.1.5/gems/rails-erd-1.5.2/lib/rails_erd/tasks.rake:55:in `block (2 levels) in <top (required)>'
/home/kavita/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/kavita/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => erd => erd:generate

Using filetype=dot, I can generate the erd.dot file but I cannot read it.

**Comment by creativeuser** [comment]
Can you post the output of `dot -V`?

**Comment by pelluch** [comment]
I have the same issue, using the gem version 1.5.2, on OS X High Sierra.
Output of dot -V:

dot - graphviz version 2.40.1 (20161225.0304)

On running with bundle exec erd --debug, I get the same stack trace as the OP.
The specific exception thrown (as seen with a byebug statement in the offending line) is:

NoMethodError Exception: undefined method `zero?' for nil:NilClass

**Comment by thbar** [comment]
I had issues generating the diagram too today, I ultimately found out [this patch](https://github.com/voormedia/rails-erd/issues/70#issuecomment-63645855) which solved it for me. Maybe it will work for you too?

**Comment by pelluch** [comment]
The patch @thbar linked to worked perfectly. Thanks!
