### ISSUE TITLE
NameError when running rails db:migrate

### ISSUE THREAD

**Issue by compostbrain** [voormedia/rails-erd#282]
I get this error: 
`bin/rails db:migrate`
`rails aborted!
NameError: uninitialized constant RailsERD
/Users/compost/Source/Go-Tournament-Manager/lib/tasks/auto_generate_diagram.rake:5:in `<top (required)>'
/Users/compost/Source/Go-Tournament-Manager/Rakefile:5:in `<top (required)>'
/Users/compost/Source/Go-Tournament-Manager/bin/rails:9:in `require'
/Users/compost/Source/Go-Tournament-Manager/bin/rails:9:in `<top (required)>'
/Users/compost/Source/Go-Tournament-Manager/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)`

I followed the install instructions and I can generate a pdf file using `bundle exec erd` but this error makes it difficult to proceed,  The app is using rails 5.1.3 and ruby 2.4.1

**Comment by hirokihokari** [comment]
I got the same issue with rails 5.1.3 ruby 2.4.1.

I know it's not supposed to for efficiency, but removing `require: false` in Gemfile solved it for me.

**Comment by compostbrain** [comment]
Thanks! That solved it for me too.

**Comment by s2t2** [comment]
Should the README be updated?

**Comment by nstoker** [comment]
I encountered the same issue, but instead of removing the `require:false` in the gem file, I changed `/lib/tasks/auto_generate_diagram.rake`:

```ruby
if Rails.env.development?
  require 'rails-erd'
  RailsERD.load_tasks
end
```
