### ISSUE TITLE
Rail-erd does not discover all models

### ISSUE THREAD

**Issue by indocomsoft** [voormedia/rails-erd#292]
Rails-erd used to work perfectly up for our project up until this commit: https://github.com/commit-tech/takoyaki/commit/51ee02cd7dd9bc864842a8e119e27b849b075a6b (it is broken since this commit). We added devise authentication at that commit.

It seems that rails-erd does not discover the other models. In commit https://github.com/commit-tech/takoyaki/commit/475f7c96eda31376a3593524c62d2dfa283c7800, on console, erd logged `Generating entity-relationship diagram for 7 models...`, but at commit https://github.com/commit-tech/takoyaki/commit/51ee02cd7dd9bc864842a8e119e27b849b075a6b it logged `Generating entity-relationship diagram for 3 models...`

**Comment by indocomsoft** [comment]
Solved this issue -- unrelated to rails-erd

**Comment by kerrizor** [comment]
@indocomsoft no worries! Thank you for taking the time to write in, regardless of the root cause!

**Comment by aaronchi** [comment]
@indocomsoft Do you know what caused the issue? I am having the same problem.

**Comment by indocomsoft** [comment]
@aaronchi one of the classes were marked as a module (some customised devise class). Somehow rails ran just fine but it interfered with this gem's class loading. After I changed module to class, rails-erd ran fine again.

**Comment by indocomsoft** [comment]
@aaronchi for reference this is the commit that fixed it https://github.com/commit-tech/takoyaki/commit/c70e1e749b5e4056d672b5163dafd955f56ee739
