### ISSUE TITLE
Install failing due to Rails version

### ISSUE THREAD

**Issue by JesseAldridge** [voormedia/rails-erd#293]
Got the following output after doing bundle install:
```
  In Gemfile:
    rails (= 3.0.20.12lts.11) was resolved to 3.0.20.12lts.11, which depends on
      activerecord (= 3.0.20.12lts.11)

    rails-erd was resolved to 1.2.2, which depends on
      activerecord (~> 3.2)
```

I can't upgrade Rails.  Any chance of getting support for Rails 3.0?

**Comment by JesseAldridge** [comment]
No, I'm working with a very large 10 year old application owned by a large company. Upgrading is not an option.

**Comment by kerrizor** [comment]
I wonder if you could try using a previous release of the gem?
