### ISSUE TITLE
ERD for latest Spree edge code only contains a few models.

### ISSUE THREAD

**Issue by wtian** [voormedia/rails-erd#3]
I used rails erd to try to generate ERD for the latest Spree edge code: 

<pre>
$ rake erd
Loading Active Record models...
Generating Entity-Relationship Diagram...
Warning: Ignoring invalid model MailMethod (table mail_methods does not exist)
Warning: Ignoring invalid association :inventory_units on Order (model InventoryUnit exists, but is not included in domain)
Warning: Ignoring invalid association :payments on Order (model Payment exists, but is not included in domain)
Warning: Ignoring invalid association :ship_address on Order (model Address exists, but is not included in domain)
Warning: Ignoring invalid association :vendor on Order (model Vendor exists, but is not included in domain)
Warning: Ignoring invalid association :shipping_method on Order (model ShippingMethod exists, but is not included in domain)
Warning: Ignoring invalid association :adjustments on Order (model Adjustment exists, but is not included in domain)
Warning: Ignoring invalid association :state_events on Order (model StateEvent exists, but is not included in domain)
Warning: Ignoring invalid association :bill_address on Order (model Address exists, but is not included in domain)
Warning: Ignoring invalid association :return_authorizations on Order (model ReturnAuthorization exists, but is not included in domain)
Warning: Ignoring invalid association :shipments on Order (model Shipment exists, but is not included in domain)
Warning: Ignoring invalid association :promotion_credits on Order (model PromotionCredit exists, but is not included in domain)
Warning: Ignoring invalid association :roles on User (model Role exists, but is not included in domain)
Warning: Ignoring invalid association :ship_address on User (model Address exists, but is not included in domain)
Warning: Ignoring invalid association :bill_address on User (model Address exists, but is not included in domain)
Warning: Ignoring invalid association :promotion_rules on Product (model PromotionRule exists, but is not included in domain)
Warning: Ignoring invalid association :vendor on Product (model Vendor exists, but is not included in domain)
Warning: Ignoring invalid association :option_types on Product (model OptionType exists, but is not included in domain)
Warning: Ignoring invalid association :properties on Product (model Property exists, but is not included in domain)
Warning: Ignoring invalid association :product_option_types on Product (model ProductOptionType exists, but is not included in domain)
Warning: Ignoring invalid association :tax_category on Product (model TaxCategory exists, but is not included in domain)
Warning: Ignoring invalid association :taxons on Product (model Taxon exists, but is not included in domain)
Warning: Ignoring invalid association :product_properties on Product (model ProductProperty exists, but is not included in domain)
Warning: Ignoring invalid association :shipping_category on Product (model ShippingCategory exists, but is not included in domain)
Warning: Ignoring invalid association :images on Product (model Image exists, but is not included in domain)
Warning: Ignoring invalid association :inventory_units on Variant (model InventoryUnit exists, but is not included in domain)
Warning: Ignoring invalid association :option_values on Variant (model OptionValue exists, but is not included in domain)
Warning: Ignoring invalid association :images on Variant (model Image exists, but is not included in domain)
Warning: Ignoring invalid association :promotion_rules on ProductGroup (model PromotionRule exists, but is not included in domain)
Warning: Ignoring invalid association :product_scopes on ProductGroup (model ProductScope exists, but is not included in domain)
</pre>

The generated diagram only contains a few models, namely: ProductGroup, Product, Variant, User, Order, LineItem

**Comment by tonytonyjan** [comment]
+1

**Comment by tonytonyjan** [comment]
temporary solution:

```
$ cp -r $(bundle show spree_core)/app/models/spree app/models/
$ bin/rake erd
```

**Comment by kerrizor** [comment]
Is this still an issue in the newest version of the gem?

**Comment by tonytonyjan** [comment]
@kerrizor yes, it is

Name      | Version
---       | ---
Rails     | 4.2.0
Ruby      | 2.2.1-p85 (x86_64-darwin14)
RubyGems  | 2.4.5
spree     | 3.0.0
rails-erd | 1.3.1

![](http://i.imgur.com/4Fl4jIu.png)

**Comment by kinduff** [comment]
@tonytonyjan Thanks! :+1:

**Comment by sebbean** [comment]
this is fixed?

**Comment by sebbean** [comment]
still having this issue
