### ISSUE TITLE
Failed: SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by Argorate** [voormedia/rails-erd#307]
```
$ bundle exec erd
Loading application in 'TMI'...
Generating entity-relationship diagram for 49 models...
Failed: SystemStackError: stack level too deep
```

But no more verbose, can you add in log the stack to see where is the circular reference?

**Comment by mathieujobin** [comment]
are you up to date? 
your output does not show 2 lines the same way as the code shows
https://github.com/voormedia/rails-erd/blob/master/lib/rails_erd/tasks.rake#L28-L31

**Comment by mathieujobin** [comment]
then, I would but a debugger, or some troubleshooting `puts` in there https://github.com/voormedia/rails-erd/blob/master/lib/rails_erd/diagram.rb#L127

or there if the above is too late

https://github.com/voormedia/rails-erd/blob/master/lib/rails_erd/domain.rb#L27

**Comment by nitsujri** [comment]
For those who get this in large applications like I did 2 debugging tools:

- `bundle exec erd --debug`
- `debugger if caller.length > 500`

The debug will grant the stacktrace. Then stick the debugger inside where it's looping.
