### ISSUE TITLE
polymorphism doesn't work with the option 'only'

### ISSUE THREAD

**Issue by Rodrigora** [voormedia/rails-erd#310]
Hi,

I'm experiencing this issue when using the following config:

```
# .erdconfig
polymorphism: true
only: "User,Client,Company,Associate,Person"
```

**Expected:** 

I diagram should be rendered using the given models and **only** their polymorphic associations

**Actual:** 

The diagram renders all polymorphic associations defined by **all** models

Is it a bug or I'm missing something? 
Thanks

**Comment by kerrizor** [comment]
It is poorly documented, but `only` expects any array of models.
