### ISSUE TITLE
Fails with Rails 5.2.2

### ISSUE THREAD

**Issue by ColinSummers** [voormedia/rails-erd#316]
Walnut:circle colin$ rake erd filetype=dot --trace

** Invoke erd (first_time)
** Invoke erd:generate (first_time)
** Invoke erd:check_dependencies (first_time)
** Execute erd:check_dependencies
** Invoke erd:options (first_time)
** Execute erd:options
** Invoke erd:load_models (first_time)
** Execute erd:load_models
Loading application environment...
** Invoke environment (first_time)
** Execute environment
Loading code in search of Active Record models...
** Execute erd:generate
rake aborted!
ArgumentError: wrong number of arguments (given 0, expected 1)
/Users/colin/Sites/circle/app/models/user.rb:154:in `hash'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/descendants_tracker.rb:42:in `accumulate_descendants'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/descendants_tracker.rb:44:in `block in accumulate_descendants'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/descendants_tracker.rb:44:in `each'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/descendants_tracker.rb:44:in `accumulate_descendants'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/descendants_tracker.rb:44:in `block in accumulate_descendants'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/descendants_tracker.rb:44:in `each'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/descendants_tracker.rb:44:in `accumulate_descendants'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/descendants_tracker.rb:16:in `descendants'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/descendants_tracker.rb:59:in `descendants'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rails-erd-1.5.2/lib/rails_erd/tasks.rake:52:in `block (2 levels) in <main>'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/colin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/colin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/colin/.rvm/gems/ruby-2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/colin/.rvm/gems/ruby-2.5.0/bin/rake:23:in `load'
/Users/colin/.rvm/gems/ruby-2.5.0/bin/rake:23:in `<main>'
/Users/colin/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
/Users/colin/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => erd => erd:generate

**Comment by kerrizor** [comment]
We rely on internal methods in `ActiveRecord` and `ActiveSupport`, so when they change, we sometimes see issues. the new v1.6.0 should address this (hopefully) and has 5.2.2 working under test.

**Comment by ColinSummers** [comment]
It worked! Thanks!
