### ISSUE TITLE
Garbled block characters generated instead of entity labels in Rails 5.1.4 / docker Alpine distro

### ISSUE THREAD

**Issue by dklanac** [voormedia/rails-erd#317]
Garbled block characters show up in `erd.pdf` when generating with Alpine distro on Docker. Here is the relevant part of the `Dockerfile` to show the `graphviz` dependency installation. Maybe `graphviz` is broken in this distro? I never had this problem when running Rails from native macOS.

```
FROM ruby:2.4.5-alpine

# Minimal requirements to run a Rails app
RUN apk add --no-cache --update \
    build-base \
    linux-headers \
    git \
    postgresql-dev \
    nodejs \
    tzdata \
    graphviz
```
<img width="1996" alt="screen shot 2019-02-06 at 8 27 32 pm" src="https://user-images.githubusercontent.com/826632/52385022-eedfbf00-2a4d-11e9-8696-33d88031d666.png">

**Comment by wkirby** [comment]
I've got the exact same problem, with an almost identical setup.

**Comment by wkirby** [comment]
I've got the exact same problem, with an almost identical setup. The issue is that Alpine doesn't have Arial installed by default. The quick and dirty solution is to run the following in your `Dockerfile`:

```
RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f
```

**Comment by dklanac** [comment]
Yep. That worked for me too. We could probably close this one out, since it's on the Alpine side.

**Comment by sushie1984** [comment]
In case of someone run into that issue and does not want to call `update-ms-fonts` as it could take some time, checkout https://wiki.alpinelinux.org/wiki/Fonts and fonts directly that you need.

In my **explicit case** for alpine-3.16 I was able to solve this by adding `apk add graphviz font-noto-extra`
