### ISSUE TITLE
Superclass mismatch for classes w/ same name defined within different modules

### ISSUE THREAD

**Issue by ProtonPunk** [voormedia/rails-erd#319]
I'm having a module/class hierarchy as follows which works just fine in dev, test and prod:

```
module A
   class Base
   end
   module B
         class Base << A::Base
         end
         class ImplX << Base
         end
   end
   module C
         class Base << A::Base
         end
         class ImplX << Base
         end
   end
```
 
Running erd::generate will give me `superclass mismatch for ImplX` as it's base is defined w/ same name in different modules.

I've tried to `exclude: "A, A::Base, A::B::Base` etc.. in the config but with no success.

Exclude seems to be applied after parsing the source tree so it doesn't help here. Is there another way to skip some parts of the source-tree from parsing ?

**Comment by kerrizor** [comment]
I'm sorry you're running into a problem!  Thanks for posting a snippet of what your relationship structure looks like; it helps immensely!

A couple ideas:
- Can you provide the stack trace from the error? It'll help narrow down the search for this.
- `exclude` wants an array of strings or symbols; if you provide it with `exclude: ["A", "A::Base"...` does that work? How about if you provide it with symbols?

**Comment by ProtonPunk** [comment]
Trying to reproduce the error in a fresh rails app i found that the issue was due to the way my app was auto-loading code (twice, using load). The code is loaded multiple times hence the error. I think you can safely disregard this bug-report. Thank you very much for picking up the issue !
