### ISSUE TITLE
Draw a Graph of a related subset

### ISSUE THREAD

**Issue by hargoniX** [voormedia/rails-erd#352]
Is it possible to only draw Graphs of a related subset with this? So instead of blacklisting / whitelisting certain models with only and exclude, track a model by either following all the objects it contains or the exact opposite, drawing all the objects that refer to it. That would be super helpful when viewing really large model structures.

**Comment by hooopo** [comment]
@hargoniX I think you can try drawerd, with grouping feature: https://help.drawerd.com/group/filter

**Comment by hargoniX** [comment]
Looks interesting, I'll take a look...although this of course defeats rails-erd's claim to be the last tool people need to draw rails erd's^^
