### ISSUE TITLE
Disabling auto-generate on db:migrate

### ISSUE THREAD

**Issue by ciembor** [voormedia/rails-erd#399]
Hello, I can't find such option in a `README` nor documentation. I think it would be useful. Did I miss something and it's already possible, or does it need a pull request (if confirmed it's a good idea).

**Comment by zewelor** [comment]
I think auto generation gets executed via rake task, installed this way:
https://github.com/voormedia/rails-erd#auto-generation

So you can probably remove file lib/tasks/auto_generate_diagram.rake and it should stop auto generation on db:migrate

**Comment by ciembor** [comment]
Thanks :).
