### ISSUE TITLE
Changing output file path.

### ISSUE THREAD

**Issue by ciembor** [voormedia/rails-erd#400]
I don't see any possibility to change the path of auto generated ERD (I want it in `doc` directory). Is there a way or should be added?

**Comment by remnantkevin** [comment]
You can use the [`--filename` option](https://voormedia.github.io/rails-erd/customise.html) to specify the path to where you want the ERD file to be generated. This path also includes the file basename. For example, when I run the following

```sh
bundle exec erd  --open --attributes content --filetype pdf --filename path/to/erd-filename
```

the diagram is generated and stored as `path/to/erd-filename.pdf`.


_Note: I've only tried this on MacOS_

**Comment by kerrizor** [comment]
The docs site is a bit outdated, but if someone wants to add this to the README... 👍
