### ISSUE TITLE
Orientation needs a square option. 

### ISSUE THREAD

**Issue by yxhuvud** [voormedia/rails-erd#49]
I have a Rails app with some 150 or so activerecord models. Neither vertical or horizontal orientation work well since there will be so much overlap between different lines since the output will either be absurdly long or absurdly high. 

I believe a square option would work a lot better.

**Comment by mathieujobin** [comment]
I wish we could revisit this idea and find a way... the PDF that I tried to print this morning had a page size of `10154 x 1315 mm (Landscape Custom)`

using `pdfposter`, I got it to be split in 2 page high and 11 pages wide.
I would have prefered something like a 4x5

Thankfully with clustering found in #320 
I could get a smaller pdf has a page size of `754 x 5887 mm (Portrait Custom)`

still being able to precise some sort of limit would be great
