### ISSUE TITLE
Only, Exclude option is not working 

### ISSUE THREAD

**Issue by railsfactory-palpandi** [voormedia/rails-erd#50]
Hi,

This libraery is very good to use but there is some issue which fine while using this library.

I am get any output based on only, exclude options.

I have use this rake command from my rails application root directory.

 bundle exec rake erd  title='ContractPort ER Diagram' exclude="StatusInfo, Setting"

Kindly replay and fix the issues ASAP.

**Comment by ktaragorn** [comment]
I get this too, exclude option ignored and I dont see the above mentioned warnings either. On 1.2.2
