### ISSUE TITLE
How to fix? ( undefined method name' for nil:NilClass )

### ISSUE THREAD

**Issue by ghost** [voormedia/rails-erd#54]
rake erd --trace
*\* Invoke erd (first_time)
*\* Invoke erd:generate (first_time)
*\* Invoke erd:options (first_time)
*\* Execute erd:options
*\* Invoke erd:load_models (first_time)
*\* Execute erd:load_models
Loading application environment...
*\* Invoke environment (first_time)
*\* Execute environment
Loading code in search of Active Record models...
*\* Execute erd:generate
Generating Entity-Relationship Diagram for 35 models...
Warning: Ignoring invalid model WiceGridSerializedQuery (table wice_grid_serialized_queries does not exist)
Warning: Ignoring invalid model Old::OldCategory (Unknown database 'snegiri_legacy')
Warning: Ignoring invalid model Old::OldField (Unknown database 'snegiri_legacy')
Warning: Ignoring invalid association :resource on ActiveAdmin::Comment (polymorphic interface Resource does not exist)
Warning: Ignoring invalid association :author on ActiveAdmin::Comment (polymorphic interface Author does not exist)
Warning: Ignoring invalid association :admins on City (uninitialized constant City::Admin)
Warning: Ignoring invalid association :assetable on Ckeditor::Asset (polymorphic interface Assetable does not exist)
Warning: Ignoring invalid association :assetable on Ckeditor::Asset (polymorphic interface Assetable does not exist)
Warning: Ignoring invalid association :assetable on Ckeditor::Asset (polymorphic interface Assetable does not exist)
rake aborted!
undefined method `name' for nil:NilClass
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bundler/gems/rails-erd-d29b0c29fcfa/lib/rails_erd/domain/specialization.rb:66:in`<=>'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bundler/gems/rails-erd-d29b0c29fcfa/lib/rails_erd/domain/specialization.rb:13:in `sort'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bundler/gems/rails-erd-d29b0c29fcfa/lib/rails_erd/domain/specialization.rb:13:in`from_models'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bundler/gems/rails-erd-d29b0c29fcfa/lib/rails_erd/domain.rb:67:in `specializations'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bundler/gems/rails-erd-d29b0c29fcfa/lib/rails_erd/diagram.rb:170:in`filtered_specializations'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bundler/gems/rails-erd-d29b0c29fcfa/lib/rails_erd/diagram.rb:132:in `generate'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bundler/gems/rails-erd-d29b0c29fcfa/lib/rails_erd/diagram.rb:119:in`create'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bundler/gems/rails-erd-d29b0c29fcfa/lib/rails_erd/diagram.rb:74:in `create'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bundler/gems/rails-erd-d29b0c29fcfa/lib/rails_erd/tasks.rake:41:in`block (2 levels) in <top (required)>'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:246:in`block in execute'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:241:in`execute'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/home/zheka/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in`mon_synchronize'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:205:in`block in invoke_prerequisites'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:203:in`invoke_prerequisites'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/home/zheka/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in`mon_synchronize'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/task.rb:170:in`invoke'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:101:in`block (2 levels) in top_level'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:101:in`block in top_level'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:95:in`top_level'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:160:in`standard_exception_handling'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/gems/rake-10.0.4/bin/rake:33:in`<top (required)>'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/bin/rake:23:in `load'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@global/bin/rake:23:in`<main>'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bin/ruby_noexec_wrapper:14:in `eval'
/home/zheka/.rvm/gems/ruby-2.0.0-p0@snegiri/bin/ruby_noexec_wrapper:14:in`<main>'
Tasks: TOP => erd => erd:generate

**Comment by vaibhav8186** [comment]
@kerrizor  @codez  This issue still exists in rails-erd (1.6.0). So can you please give your thoughts on that.

**Comment by pooja-mane** [comment]
@kerrizor @codez @rolftimmermans I am also facing the same issue as 
`NoMethodError:` undefined method name' for nil:NilClass`
rails-erd(1.6.0)

**Comment by karamat** [comment]
I have fixed this issue temporarily and successfully generate ERD diagram. 2 things I have done.

1- Tracing back to the point of crash, and found that it is happening due to `relationship.destination` `nil` . So I handled nil check by searching this in all the code

2- After this it crashed again in this method 

```
def foreign_key_required?(association)
        if !association.active_record.abstract_class? and association.belongs_to?
            column = association.active_record.columns_hash[association.send(Domain.foreign_key_method_name)] and !column.null
        end
      end
```

I rescued the line that was crashing

```
def foreign_key_required?(association)
        if !association.active_record.abstract_class? and association.belongs_to?
          begin
            column = association.active_record.columns_hash[association.send(Domain.foreign_key_method_name)] and !column.null
          rescue Exception => e
            p e.message
          end
        end
      end
```
