### ISSUE TITLE
Unable to activate ...  activerecord-2.2.2 conflicts with activerecord (>= 3.0)

### ISSUE THREAD

**Issue by lmorris99** [voormedia/rails-erd#68]
ON RHEL Linux, using rbenv and ruby 2.1.0.  
"bundle install" works, but "rake erd" then fails.

 bundle install
Using i18n (0.6.9)
Using minitest (4.7.5)
Using multi_json (1.8.4)
Using atomic (1.1.14)
Using thread_safe (0.1.3)
Using tzinfo (0.3.38)
Using activesupport (4.0.2)
Using builder (3.1.4)
Using activemodel (4.0.2)
Using activerecord-deprecated_finders (1.0.3)
Using arel (4.0.2)
Using activerecord (4.0.2)
Using choice (0.1.6)
Using ruby-graphviz (1.0.9)
Using rails-erd (1.1.0)
Using bundler (1.5.3)
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
[art@ip-10-112-49-74 ~]$ rake erd
rake aborted!
Unable to activate rails-erd-1.1.0, because activesupport-2.2.2 conflicts with activesupport (>= 3.0), activerecord-2.2.2 conflicts with activerecord (>= 3.0)
/home/art/vendor/rails/activesupport/lib/active_support/dependencies.rb:153:in `block in require'
/home/art/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
/home/art/vendor/rails/activesupport/lib/active_support/dependencies.rb:153:in `require'
/home/art/vendor/rails/activesupport/lib/active_support/dependencies.rb:153:in `block in require'
/home/art/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
/home/art/vendor/rails/activesupport/lib/active_support/dependencies.rb:153:in `require'
/home/art/Rakefile:11:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by kerrizor** [comment]
Thanks to @a2ikm in #120 we now have Rails 4.x support. Thank you for the heavy lifting!
