### ISSUE TITLE
NoMethodError: undefined method `primary' for #<ActiveRecord::ConnectionAdapters::Column:0x0000000794a910>

### ISSUE THREAD

**Issue by LimeBlast** [voormedia/rails-erd#85]
I've just updated Rails from 4.1.0 to 4.2.0.beta2, and now the ERD generator isn't working any longer. I get the following error:

    Failed: NoMethodError: undefined method `primary' for #<ActiveRecord::ConnectionAdapters::Column:0x00000007b842f8>

**Comment by abevoelker** [comment]
Would be cool to see this merged!

    gem 'rails-erd', github: 'ready4god2513/rails-erd', branch: 'rails-4.2-support-fix'

is still working fine, but can't use newer rails-erd features like the `.erdconfig` file.

**Comment by kerrizor** [comment]
I'm planning on getting this (and a few other changes) merged into a 2.0 release which will officially support Rails 4.x

**Comment by abevoelker** [comment]
Great, nice work! :metal: Love the project.

**Comment by LimeBlast** [comment]
:+1:

**Comment by supertinou** [comment]
:+1:

**Comment by m-shirshendu** [comment]
:+1:

**Comment by chrishough** [comment]
On my new computer I just used your branch `gem 'rails-erd', github: 'ready4god2513/rails-erd', branch: 'rails-4.2-support-fix'` @abevoelker and it worked perfectly, thank you

**Comment by abevoelker** [comment]
@chrishough It's @ready4god2513's branch but yeah no problem

**Comment by chrishough** [comment]
oops, my bad. sorry for the confusion, thank you @ready4god2513

**Comment by arelenglish** [comment]
:+1: Thanks @abevoelker !

**Comment by kerrizor** [comment]
Thanks to @a2ikm in #120 we now have Rails 4.x support. Thank you for the heavy lifting!
