### ISSUE TITLE
Error occurred while loading application: No such file to load -- zip/zip (LoadError)

### ISSUE THREAD

**Issue by asamats** [voormedia/rails-erd#89]
I run: bundle exec rake erd filetype=pdf

Loading code in search of Active Record models...
rake aborted!
Loading models failed!
Error occurred while loading application: No such file to load -- zip/zip (LoadError)

Can't understand why zip...

Use:
rails (4.0.12)
rails-erd (1.1.0)
rubyzip (1.1.6)

**Comment by kerrizor** [comment]
Thanks to @a2ikm in #120 we now have Rails 4.x support. Thank you for the heavy lifting!

**Comment by shamouda** [comment]
I am getting a similar error with rails 5.2.3, which is currently supported by rails-erd.

I am trying to generate the ERD diagram of the Discourse application [https://github.com/discourse/discourse]. This application uses a number of plugins including one called "poll". I am getting this error while loading the models:

Loading application environment...
Loading code in search of Active Record models...
rails aborted!
Loading models failed!
Error occurred while loading application: No such file to load -- poll.rb (LoadError)

My environment:
Operating system: macOS, Mojava, version 10.14.4
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
$ rails -v
Rails 5.2.3
$ gem -v
2.7.9
$ bundle -v
Bundler version 1.17.3

Could you please advice on what I may be missing here?
